server:
  port: 7070
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
  jackson:
    serialization:
      fail-on-empty-beans: false
  profiles:
    active: local