apiVersion: v1
kind: Service
metadata:
  name: tmbr-customer-api
  labels:
    app: tmbr-customer-api
spec:
  ports:
  - name: http #ddkanrjsk 아무거나 
    port: 80 #80으로 편함  
    targetPort: 7070
    nodePort: 31581
  selector:
    app: tmbr-customer-api
    version: '0.1'
  type: NodePort
#NodePort